FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@10.32.1 --activate

WORKDIR /app

ENV HOSTNAME=0.0.0.0

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

VOLUME /app/node_modules

CMD ["pnpm", "dev"]
